# Generated by Django 2.2.4 on 2019-09-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=100, verbose_name='Nombre y apellido')),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(verbose_name='Fecha de publicación')),
            ],
        ),
    ]
