# Generated by Django 2.2.4 on 2019-09-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obra_social', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Obra_Social',
        ),
    ]
