# Generated by Django 2.2.4 on 2019-09-24 00:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='clinica',
        ),
        migrations.AddField(
            model_name='customuser',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 9, 24, 0, 24, 16, 637859, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
