# Generated by Django 2.2.4 on 2019-09-24 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0002_auto_20190924_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='odonto.Clinica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='norma_trabajo',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='odonto.Clinica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra_social',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='odonto.Clinica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odontologo',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='odonto.Clinica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='odonto.Clinica'),
            preserve_default=False,
        ),
    ]
