# Generated by Django 2.2.4 on 2020-01-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0002_auto_20200110_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('detalle', models.TextField(blank=True, max_length=1000)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odonto.Ficha')),
                ('norma_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='odonto.Norma_Trabajo')),
                ('obra_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='odonto.Obra_Social')),
            ],
        ),
    ]
