# Generated by Django 2.2.4 on 2019-09-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0003_auto_20190924_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='clinica',
        ),
    ]
