# Generated by Django 2.2.4 on 2020-01-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0003_auto_20200115_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='imagenes_fichas/'),
        ),
    ]
