# Generated by Django 2.2.4 on 2019-09-24 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0004_remove_customuser_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='odonto.Clinica'),
            preserve_default=False,
        ),
    ]
