# Generated by Django 2.2.4 on 2020-01-19 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0004_auto_20200118_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='creada',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 1, 19, 19, 53, 15, 915534, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
