# Generated by Django 2.2.4 on 2019-09-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0005_customuser_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra_social',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='odontologo',
            name='dni',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='odontologo',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='odontologo',
            name='matricula',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='odontologo',
            name='telefono',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obras_sociales',
            field=models.ManyToManyField(blank=True, to='odonto.Obra_Social'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='odontologos',
            field=models.ManyToManyField(blank=True, to='odonto.Odontologo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
