# Generated by Django 2.2.4 on 2020-01-21 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0005_imagen_creada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='detalle',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='obra_social',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='norma_trabajo',
        ),
        migrations.AddField(
            model_name='consulta',
            name='nro_diente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='odonto.Plan'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='detalle',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
