# Generated by Django 2.2.4 on 2019-09-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0006_auto_20190925_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=1000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odonto.Clinica')),
                ('norma_trabajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='odonto.Norma_Trabajo')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odonto.Odontologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odonto.Paciente')),
            ],
        ),
    ]
