# Generated by Django 2.2.4 on 2020-05-09 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0007_ficha_nro_afiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteobrasocial',
            name='obra_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odonto.Obra_Social'),
        ),
        migrations.AlterField(
            model_name='pacienteobrasocial',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odonto.Plan'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, max_length=1000)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odonto.Clinica')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odonto.Odontologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odonto.Paciente')),
            ],
        ),
    ]
