# Generated by Django 2.2.4 on 2019-09-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0007_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='obra_social',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='odonto.Obra_Social'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='detalle',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
