# Generated by Django 2.2.4 on 2019-09-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0008_auto_20190929_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
