# Generated by Django 2.2.4 on 2020-05-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0008_auto_20200509_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
