# Generated by Django 2.2.4 on 2019-10-10 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0009_auto_20190929_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='norma_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='odonto.Norma_Trabajo'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='odonto.Obra_Social'),
        ),
        migrations.AlterField(
            model_name='norma_trabajo',
            name='descripcion',
            field=models.TextField(max_length=2000, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='obra_social',
            name='codigo',
            field=models.IntegerField(error_messages={'unique': 'Ya existe una obra social con el codigo ingresado.'}, unique=True),
        ),
        migrations.AlterField(
            model_name='obra_social',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
