# Generated by Django 2.2.4 on 2020-05-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0009_paciente_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra_social',
            name='codigo',
            field=models.IntegerField(blank=True),
        ),
    ]
