# Generated by Django 2.2.4 on 2020-05-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0010_auto_20200510_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra_social',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
