# Generated by Django 2.2.4 on 2019-10-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0011_odontologo_obras_sociales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='norma_trabajo',
            name='vencimiento',
        ),
        migrations.AddField(
            model_name='norma_trabajo',
            name='años',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='norma_trabajo',
            name='dias',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='norma_trabajo',
            name='mes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
