# Generated by Django 2.2.4 on 2020-05-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0012_auto_20200510_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontologo',
            name='dni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='odontologo',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='odontologo',
            name='matricula',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='odontologo',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
