# Generated by Django 2.2.4 on 2019-10-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0012_auto_20191018_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='norma_trabajo',
            old_name='mes',
            new_name='meses',
        ),
    ]
