# Generated by Django 2.2.4 on 2019-10-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0013_auto_20191020_1723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='norma_trabajo',
            unique_together={('codigo', 'obra_social', 'clinica')},
        ),
    ]
