# Generated by Django 2.2.4 on 2020-05-16 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0014_auto_20200515_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='odontologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='odonto.Odontologo'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='odonto.Paciente'),
        ),
    ]
