# Generated by Django 2.2.4 on 2019-11-10 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0014_auto_20191020_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='norma_trabajo',
            options={'ordering': ('obra_social__nombre',)},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='paciente',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='obra_social',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='obra_social',
            unique_together={('codigo', 'clinica')},
        ),
    ]
