# Generated by Django 2.2.4 on 2020-05-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0015_auto_20200516_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='todo_el_dia',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
