# Generated by Django 2.2.4 on 2020-05-23 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0016_turno_todo_el_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('nro', models.IntegerField()),
                ('valor', models.CharField(blank=True, max_length=100, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odonto.Ficha')),
            ],
        ),
    ]
