# Generated by Django 2.2.4 on 2020-05-25 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0018_auto_20200525_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='ficha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='odonto.Ficha'),
        ),
    ]
