# Generated by Django 2.2.4 on 2020-05-25 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0019_odontograma_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontograma',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odonto.Ficha'),
        ),
    ]
