# Generated by Django 2.2.4 on 2020-05-25 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0020_auto_20200525_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odontograma',
            name='ficha',
        ),
        migrations.AddField(
            model_name='ficha',
            name='odontograma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='odonto.Odontograma'),
        ),
    ]
