# Generated by Django 2.2.4 on 2019-11-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0020_auto_20191123_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra_social',
            name='usa_autorizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='obra_social',
            name='usa_bonos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='obra_social',
            name='usa_coseguro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='obra_social',
            name='usa_planes',
            field=models.BooleanField(default=False),
        ),
    ]
