# Generated by Django 2.2.4 on 2019-11-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0021_auto_20191123_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='iva',
            field=models.CharField(choices=[('GR', 'Disponible'), ('NG', 'Alquilada'), ('EX', 'Vendida')], default='GR', max_length=2),
        ),
    ]
