# Generated by Django 2.2.4 on 2020-05-25 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0022_auto_20200525_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='odontologo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='odonto.Odontologo'),
            preserve_default=False,
        ),
    ]
