# Generated by Django 2.2.4 on 2019-11-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0023_auto_20191124_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='iva',
            field=models.CharField(blank=True, choices=[('GR', 'Gravado'), ('NG', 'No gravado'), ('EX', 'Exento')], max_length=2, null=True),
        ),
    ]
