# Generated by Django 2.2.4 on 2020-07-06 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0023_ficha_odontologo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta_Corriente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('ingreso_egreso', models.CharField(blank=True, choices=[(1, 'Ingreso'), (2, 'Egreso')], max_length=2, null=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='odonto.Paciente')),
            ],
        ),
    ]
