# Generated by Django 2.2.4 on 2019-11-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0024_auto_20191124_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('nombre',)},
        ),
        migrations.AddField(
            model_name='plan',
            name='paga_coseguro',
            field=models.BooleanField(null=True, verbose_name='Paga coseguro'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='iva',
            field=models.CharField(blank=True, choices=[('', 'Seleccione IVA'), ('GR', 'Gravado'), ('NG', 'No gravado'), ('EX', 'Exento')], max_length=2, null=True),
        ),
    ]
