# Generated by Django 2.2.4 on 2020-07-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0025_auto_20200708_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_corriente',
            name='ingreso_egreso',
            field=models.CharField(blank=True, choices=[(1, 'Ingreso'), (2, 'Egreso')], max_length=20, null=True),
        ),
    ]
