# Generated by Django 2.2.4 on 2019-12-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0025_auto_20191125_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacienteobrasocial',
            name='obra_social',
        ),
        migrations.AlterField(
            model_name='plan',
            name='paga_coseguro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Paga coseguro'),
        ),
    ]
