# Generated by Django 2.2.4 on 2019-12-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0026_auto_20191214_2201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PacienteObraSocial',
            new_name='PacientePlan',
        ),
    ]
