# Generated by Django 2.2.4 on 2019-12-15 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0027_auto_20191214_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='mail',
        ),
    ]
